#!/bin/sh

start() {
    while :; do
        openvt -w -f -c 2 -- sh -c 'exec getty 38400 tty2' >> /etc/npl-init/log 2>&1 || sleep 1
    done &
}

stop() {
    pkill -f "openvt.*-c 2" 2>> /etc/npl-init/log
    pkill -f "getty.*tty2" 2>> /etc/npl-init/log
}
