#!/bin/sh

start() {
    while :; do
        openvt -w -f -c 4 -- sh -c 'exec getty 38400 tty4' >> /etc/npl-init/log 2>&1 || sleep 1
    done &
}

stop() {
    pkill -f "openvt.*-c 4" 2>> /etc/npl-init/log
    pkill -f "getty.*tty4" 2>> /etc/npl-init/log
}
