#!/bin/sh

start() {
    while :; do
        openvt -w -f -c 5 -- sh -c 'exec getty 38400 tty5' >> /etc/npl-init/log 2>&1 || sleep 1
    done &
}

stop() {
    pkill -f "openvt.*-c 5" 2>> /etc/npl-init/log
    pkill -f "getty.*tty5" 2>> /etc/npl-init/log
}
