#!/bin/sh

start() {
    while :; do
        openvt -w -f -c 6 -- sh -c 'exec getty 38400 tty6' >> /etc/npl-init/log 2>&1 || sleep 1
    done &
}

stop() {
    pkill -f "openvt.*-c 6" 2>> /etc/npl-init/log
    pkill -f "getty.*tty6" 2>> /etc/npl-init/log
}
